export const DNR_UPDATE_SESSION_RULES_TIMEOUT_MS = 5_000
export const DNR_UPDATE_SESSION_RULES_MAX_ATTEMPTS = 2
export const DNR_UPDATE_SESSION_RULES_RETRY_DELAY_MS = 250

export const DNR_UPDATE_SESSION_RULES_TIME_BUDGET_MS =
  DNR_UPDATE_SESSION_RULES_TIMEOUT_MS * DNR_UPDATE_SESSION_RULES_MAX_ATTEMPTS +
  DNR_UPDATE_SESSION_RULES_RETRY_DELAY_MS *
    (DNR_UPDATE_SESSION_RULES_MAX_ATTEMPTS - 1)
