name: Bug Report / Bug 反馈
description: Report a bug to help us improve / 报告 bug 帮助我们改进
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

        感谢您抽出时间填写此 bug 报告！请尽可能提供详细信息。

  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist / 提交前检查清单
      description: Please confirm the following before submitting / 提交前请确认以下内容
      options:
        - label: I have searched existing issues to ensure this is not a duplicate / 我已检索现有 issue 确认这不是重复问题
          required: true
        - label: I have tested with the latest release version or main branch / 我已使用最新 release 版本或 main 分支的最新版测试
          required: true
        - label: This bug still exists in the latest version / 该 bug 在最新版本中仍然存在
          required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser / 浏览器
      description: Which browser are you using? / 您使用的是哪个浏览器？
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Other / 其他
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version / 浏览器版本
      description: What version of the browser are you using? / 您使用的浏览器版本是什么？
      placeholder: e.g., Chrome 120.0.6099.109
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version / 扩展版本
      description: |
        What version of the extension are you using? You can find this in:
        - Chrome: chrome://extensions/
        - Firefox: about:addons
        - Edge: edge://extensions/

        您使用的扩展版本是什么？您可以在以下位置找到：
        - Chrome: chrome://extensions/
        - Firefox: about:addons
        - Edge: edge://extensions/
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description / Bug 描述
      description: A clear and concise description of what the bug is / 清晰简洁地描述这个 bug 是什么
      placeholder: Describe the bug... / 描述该 bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce / 复现步骤
      description: Steps to reproduce the behavior / 复现该行为的步骤
      placeholder: |
        1. Go to... / 前往...
        2. Click on... / 点击...
        3. Scroll down to... / 滚动到...
        4. See error / 看到错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior / 预期行为
      description: A clear and concise description of what you expected to happen / 清晰简洁地描述您期望发生什么
      placeholder: Describe what you expected... / 描述您的预期...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior / 实际行为
      description: A clear and concise description of what actually happened / 清晰简洁地描述实际发生了什么
      placeholder: Describe what actually happened... / 描述实际发生了什么...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / 截图
      description: If applicable, add screenshots to help explain your problem / 如果适用，请添加截图以帮助解释您的问题
      placeholder: Drag and drop images here or paste image URLs / 在此处拖放图像或粘贴图像 URL

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context / 其他信息
      description: Add any other context about the problem here / 在此处添加有关该问题的任何其他信息
      placeholder: Any additional information... / 任何其他信息...
