name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout 当前仓库代码
      - uses: actions/checkout@v4

      # 使用 release-please 管理版本号和 release PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # 默认 GITHUB_TOKEN 即可
          token: ${{ secrets.GITHUB_TOKEN }}
          # 适配 Node.js 项目
          release-type: node
